apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-world

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app: hello-world
  environment: dev
